server:
  port: 9010

app:
  openapi:
    title: Merchant Service
    description: Merchant onboarding and authentication API
    version: v1

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/paygrid-merchant-db
    username: ${PSQL_USER}
    password: ${PSQL_PASSWORD}

jwt:
  secret-key: ${JWT_SECRET}

webhook:
  secret-encryption-key: ${WEBHOOK_SECRET}

---

spring:
  config:
    activate:
      on-profile: k8s
  datasource:
    url: jdbc:postgresql://postgres.paygrid-core.svc.cluster.local:5432/paygrid-merchant-db
    username: merchant_user
    password: ${MERCHANT_DB_PASSWORD}

jwt:
  secret-key: ${JWT_SECRET}

webhook:
  secret-encryption-key: ${WEBHOOK_SECRET}