server:
  port: 8084

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/pg-vault-db?currentSchema=vault_service
    username: ${PSQL_USER}
    password: ${PSQL_PASSWORD}

vault:
  master-key: ${MASTER_KEY}

resilience4j:
  thread-pool-bulkhead:
    instances:
      vault-card-processor:
        core-thread-pool-size: 5
        max-thread-pool-size: 10
        queue-capacity: 20
